# Generated by Django 3.2.10 on 2021-12-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='text',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
