# Generated by Django 3.2.10 on 2021-12-29 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sample_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='text',
        ),
    ]
